"""
Threat Data Models
"""
from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime
from enum import Enum


class SeverityLevel(str, Enum):
    """
    Threat severity classification.

    Business Definition:
    - CRITICAL: Active breach requiring immediate response (SLA: 15 min)
    - HIGH: Active attack requiring urgent response (SLA: 1 hour)
    - MEDIUM: Suspicious activity requiring investigation (SLA: 4 hours)
    - LOW: Minor anomaly for review (SLA: 24 hours)
    - INFO: Informational event, no action required
    """
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"


class ThreatType(str, Enum):
    """
    Classification of threat types.

    Maps to MITRE ATT&CK framework techniques.
    """
    BRUTE_FORCE = "BRUTE_FORCE"           # T1110 - Credential stuffing/spraying
    SQL_INJECTION = "SQL_INJECTION"       # T1190 - Exploit public-facing app
    DDOS_ATTACK = "DDOS_ATTACK"           # T1498 - Network denial of service
    RANSOMWARE = "RANSOMWARE"             # T1486 - Data encrypted for impact
    PORT_SCAN = "PORT_SCAN"               # T1046 - Network service discovery
    MALWARE = "MALWARE"                   # T1204 - Malicious code execution
    DATA_EXFILTRATION = "DATA_EXFILTRATION"  # T1041 - Exfiltration
    AUTHENTICATION = "AUTHENTICATION"     # Authentication-related events
    FIREWALL_EVENT = "FIREWALL_EVENT"    # Firewall logs
    API_REQUEST = "API_REQUEST"          # API security events
    LOGIN_ATTEMPT = "LOGIN_ATTEMPT"      # Login events
    NORMAL_TRAFFIC = "NORMAL_TRAFFIC"    # Benign traffic
    NETWORK_ANOMALY = "NETWORK_ANOMALY"  # Network anomalies


class RiskLevel(str, Enum):
    """
    Aggregate risk level for the organization.

    Displayed on the main dashboard gauge.
    """
    NORMAL = "NORMAL"         # 0-30: Standard operations, minimal threats
    ELEVATED = "ELEVATED"     # 31-60: Above average threat activity
    SUSPICIOUS = "SUSPICIOUS" # 61-85: Active threats being investigated
    CRITICAL = "CRITICAL"     # 86-100: Incident in progress


class SecurityEvent(BaseModel):
    """
    Raw security event from Kafka.

    This is the input format from data sources before AI analysis.
    """
    event_id: str
    timestamp: datetime
    event_type: str
    source_ip: str
    destination_ip: Optional[str] = None
    destination_port: Optional[int] = None
    protocol: str = "TCP"
    payload: Dict[str, Any] = Field(default_factory=dict)
    metadata: Dict[str, Any] = Field(default_factory=dict)

    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class GeminiAnalysis(BaseModel):
    """
    AI analysis result from Gemini.

    Contains the complete threat intelligence generated by the AI engine.
    """
    severity: SeverityLevel
    threat_type: ThreatType
    confidence: float = Field(ge=0.0, le=1.0, description="AI confidence score")
    description: str
    contextual_analysis: str
    contributing_signals: List[str]
    recommended_actions: List[str]
    mitre_attack_id: Optional[str] = None
    mitre_attack_name: Optional[str] = None
    audit_ref: str = "GEMINI-PRO-ENGINE"


class Threat(BaseModel):
    """
    Analyzed threat with AI enrichment.

    This is the complete threat object stored in Firestore and
    displayed in the dashboard.
    """
    id: str
    event_id: str
    timestamp: datetime

    # Classification
    severity: SeverityLevel
    threat_type: ThreatType
    risk_score: int = Field(ge=0, le=100)

    # Source information
    source_ip: str
    source_country: Optional[str] = None
    source_country_code: Optional[str] = None
    source_zone: Optional[str] = None

    # Target information
    destination_ip: Optional[str] = None
    destination_port: Optional[int] = None

    # AI Analysis
    confidence: float
    description: str
    contextual_analysis: str
    contributing_signals: List[str]
    mitre_attack_id: Optional[str] = None
    mitre_attack_name: Optional[str] = None

    # Actions
    recommended_actions: List[str]
    auto_blocked: bool = False

    # Metadata
    processing_time_ms: int
    analyzed_at: datetime
    audit_ref: str = "GEMINI-PRO-ENGINE"

    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class RiskIndex(BaseModel):
    """Real-time risk index for the organization."""
    value: int = Field(ge=0, le=100)
    level: RiskLevel
    trend: str  # RISING, FALLING, STABLE
    last_updated: datetime

    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }
